### ISSUE TITLE
change block indent 2 to 4

### ISSUE THREAD

**Issue by leo1515416043** [jdneo/vscode-checkstyle#187] opened 2019-07-25 08:06 UTC
![image](https://user-images.githubusercontent.com/48787027/61857139-1f30f200-aef6-11e9-9a15-9c54647f5ef8.png)

![image](https://user-images.githubusercontent.com/48787027/61857184-3243c200-aef6-11e9-8e47-de356053a73c.png)

**Comment by jdneo** [comment] 2019-07-25 08:28
Hi @leo1515416043

Thank you for your feedback. Could you please provide more information about your problem? Like:
- the expected behavior
- the actual behavior
- repro steps

**Comment by leo1515416043** [comment] 2019-07-25 08:40
* the expected behavior
block indent is 4 spaces
* the actual behavior 
2 spaces
* vscode settings
![image](https://user-images.githubusercontent.com/48787027/61859557-ecd5c380-aefa-11e9-95e1-2a89f5816a81.png)

**Comment by jdneo** [comment] 2019-07-25 08:47
Could you provide your checkstyle configuration file?

**Comment by leo1515416043** [comment] 2019-07-25 08:50
I use google settings, with custom vscode settings

![image](https://user-images.githubusercontent.com/48787027/61860200-29ee8580-aefc-11e9-9d1a-bbfdff7a9010.png)

**Comment by jdneo** [comment] 2019-07-25 08:52
This is because the google's rule restrict that the offset is 2: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml#L185-L192

If you want to change it to 4, you need to provide your own configuration file.

The `java.checkstyle.properties` is not intended to be used to change the rule.

**Comment by jdneo** [comment] 2019-07-25 08:57
Closing since it seems that it's out of the extensions scope. If you have more questions, just feel free to ask.

Thanks.

**Closed by jdneo** 2019-07-25 08:57 UTC

**Comment by leo1515416043** [comment] 2019-07-25 09:02
3ks
`The java.checkstyle.properties is not intended to be used to change the rule.` I don't understand。
![image](https://user-images.githubusercontent.com/48787027/61861173-e0069f00-aefd-11e9-8601-af67fea0ce9b.png)

**Comment by jdneo** [comment] 2019-07-25 09:06
Something like this: https://maven.apache.org/plugins/maven-checkstyle-plugin/examples/custom-property-expansion.html

**Comment by leo1515416043** [comment] 2019-07-25 09:08
So There is no way to edit in vscode with json format?

**Comment by jdneo** [comment] 2019-07-25 09:10
As far as I know, Checkstyle will only honor xml as the configuration file.

**Comment by leo1515416043** [comment] 2019-07-25 09:15
3ks
