### ISSUE TITLE
[Checkstyle] Fails on load when vscode opens last sessions java file

### ISSUE THREAD

**Issue by agreedSkiing** [jdneo/vscode-checkstyle#343] opened 2023-03-24 10:23 UTC
The plugin does not seem to work fine when a java is file is the first file that VSCode displays on load, it creates a stacktrace in the plugins output. I have noted some workarounds in the workaround section.

## Reproducer
1. Start VSCode in project with java file open

### Reproducer project
https://github.com/agreedSkiing/checkstyle-reproducer-error

### VSCode 
```text
Version: 1.76.2 (user setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No
```

### Checkstyle
```text
Name: Checkstyle for Java
Id: shengchen.vscode-checkstyle
Description: Provide real-time feedback about Checkstyle violations and quick fix actions
Version: 1.4.1
Publisher: ShengChen
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=shengchen.vscode-checkstyle
```

### Red hat
```text
Name: Language Support for Java(TM) by Red Hat
Id: redhat.java
Description: Java Linting, Intellisense, formatting, refactoring, Maven/Gradle support and more...
Version: 1.16.0
Publisher: Red Hat
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=redhat.java
```

## Workaround
1. Start VSCode without open files
2. Start VSCode in a non java file
3. Save checkstyle.xml file without any changes.

**Comment by janderssonse** [comment] 2023-03-25 04:53
I can also verify this error, it seem reproducable - I tested this example project (on a slightly different base configuration - Ubuntu 22.04 - latest update, WSL 1.1.3.0, vscode 1.76.2, Extension Red Hat Java Lang. extension 1.16.0). 

By adding a  few checkstyle errors to the file ( let's say multiple ;;;;;; and reorder of imports), leaving the java file open, closing vscode and reopen vscode (i.e autorestoring the last session with the Java-file open, the checkstyle plugin would halt and show similar error report like above in its output.

**Comment by jdneo** [comment] 2023-03-28 05:49
Should be the same as https://github.com/jdneo/vscode-checkstyle/issues/341.

I'm working on a fix

**Closed by jdneo** 2023-03-28 05:49 UTC
Labels: duplicate

**Comment by jdneo** [comment] 2023-03-28 06:44
[vscode-checkstyle-1.4.2.vsix.zip](https://github.com/jdneo/vscode-checkstyle/files/11086175/vscode-checkstyle-1.4.2.vsix.zip)

I've worked for a fix for this issue. Please check if the problem is solved or not and let me know.

> Note: The default Checkstyle version is changed to `9.3`. If that does not apply to your Checkstyle configuration, please change the used version accordingly.

**Comment by agreedSkiing** [comment] 2023-03-28 11:48
> [vscode-checkstyle-1.4.2.vsix.zip](https://github.com/jdneo/vscode-checkstyle/files/11086175/vscode-checkstyle-1.4.2.vsix.zip)
> 
> I've worked for a fix for this issue. Please check if the problem is solved or not and let me know.
> 
> > Note: The default Checkstyle version is changed to `9.3`. If that does not apply to your Checkstyle configuration, please change the used version accordingly.

That fixed the issue

**Comment by janderssonse** [comment] 2023-03-29 01:09
+1, seems to work now, thanks!
