### ISSUE TITLE
Checkstyle wont start on custom Checkstyle config.

### ISSUE THREAD

**Issue by DaniGTA** [jdneo/vscode-checkstyle#308] opened 2021-02-16 08:23 UTC
I set config path and version.

```
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
    at w._executeContributedCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:98433)
    at runMicrotasks (<anonymous>)
    at runNextTicks (internal/process/task_queues.js:62:5)
    at processImmediate (internal/timers.js:429:9)
    at Object.syncServer (c:\Users\x\.vscode-insiders\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:1:81077)
    at Object.refresh (c:\Users\x\.vscode-insiders\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:1:79786)
```

VSCode version: 1.54.0-insider
Java version: 8 for Projekt and 11 for VSCode

**Comment by paulheg** [comment] 2021-02-18 12:02
I seem to have a very similar issue when using a custom checkstyle file.

The built in Google and Sun checkstyles work though.

```
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
	at b._executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:86:88571)
	at async Object.syncServer (c:\Users\Paul\.vscode\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:1:81077)
	at async Object.refresh (c:\Users\Paul\.vscode\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:1:79786)
```

VSCode Version: 1.53.2 (user setup)
Java Version 15

**Comment by pappattila** [comment] 2021-02-22 21:58
same, can't use file just built in styles

**Comment by jdneo** [comment] 2021-02-23 01:35
What's your extension setting and the rules file content?

**Comment by DaniGTA** [comment] 2021-02-23 08:38
### Extension Settings

    "java.checkstyle.configuration": "${workspaceFolder}\\checkstyle.xml",


### Checkstyle Config

**checkstyle.xml**
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE module PUBLIC "-//Puppy Crawl//DTD Check Configuration 1.3//EN" "http://www.puppycrawl.com/dtds/configuration_1_3.dtd">

<!-- This configuration file was written by the eclipse-cs plugin configuration
	editor -->
<module name="Checker">
	<property name="severity" value="warning" />
	<module name="SuppressionFilter">
		<property name="file"
			value="${config_loc}/checkstyle-suppressions.xml" />
	</module>
	<module name="LineLength">
		<property name="severity" value="ignore" />
		<property name="max" value="150" />
		<metadata name="net.sf.eclipsecs.core.lastEnabledSeverity"
			value="inherit" />
	</module>
</module>
```

**checkstyle-suppressions.xml**
```
<?xml version="1.0"?>

<!DOCTYPE suppressions PUBLIC
        "-//Puppy Crawl//DTD Suppressions 1.1//EN"
        "http://www.puppycrawl.com/dtds/suppressions_1_1.dtd">

<suppressions>
    <suppress files="[/\\]target[/\\]" checks=".*"/>
</suppressions>
```

**Comment by jdneo** [comment] 2021-02-23 09:00
Sees like it's because `${config_loc}` cannot be resolved.

How about adding the following vscode setting and try again?

```
"java.checkstyle.properties": {
    "config_loc": "${workspaceFolder}"
},
```

**Comment by DaniGTA** [comment] 2021-02-23 09:09
### Extension Settings
```
"java.checkstyle.configuration": "${workspaceFolder}\\checkstyle.xml",
"java.checkstyle.properties": {
    "config_loc": "${workspaceFolder}"
},
```
### Error

```
Error: Running the contributed command: 'java.execute.workspaceCommand' failed.
    at w._executeContributedCommand (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:85:99291)
    at Object.syncServer (c:\Users\x\.vscode-insiders\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:1:81077)
    at Object.refresh (c:\Users\x\.vscode-insiders\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:1:79786)
    at Object.initialize (c:\Users\x\.vscode-insiders\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:1:77932)
    at g (c:\Users\x\.vscode-insiders\extensions\shengchen.vscode-checkstyle-1.4.0\dist\extension.js:29:20243)
```

**Comment by jdneo** [comment] 2021-02-23 09:12
What's the value of `config_loc` defined in your project? You need to change the value according to your project setting

**Comment by DaniGTA** [comment] 2021-02-23 09:13
its `${workspaceFolder}` the `checkstyle-suppressions.xml` is in the same path as `checkstyle.xml`

**Comment by jdneo** [comment] 2021-02-23 09:18
Also please don't forget to use a more latest version of Checkstyle. For example

"java.checkstyle.version": "8.40",

**Comment by DaniGTA** [comment] 2021-02-23 09:19
![image](https://user-images.githubusercontent.com/20490672/108823357-980b9a80-75c0-11eb-8a5a-bb5329505a79.png)

I reloaded VSCode.

**Comment by jdneo** [comment] 2021-02-23 09:34
Have no idea why 🤔. It works on my side.

![image](https://user-images.githubusercontent.com/6193897/108824836-2867d080-75fd-11eb-84d8-a293e6d1a049.png)

One last shoot: try to trigger this command: `Java: Clean Java Language Server Workspace`

**Comment by pappattila** [comment] 2021-02-23 09:48
do you run it on win too?

**Comment by DaniGTA** [comment] 2021-02-23 09:50
The command didnt help. Still same error in the log.

I have this error from the dev console:

```
{  message: '[Error - 10:45:48] 23.02.2021, 10:45:48 Problems occurred when invoking code from plug-in: "org.eclipse.jdt.ls.core".\n' +    'null\n' +    'java.lang.reflect.InvocationTargetException
' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
' +    '\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
' +    '\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)
' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:58)
' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
' +    '\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
' +    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
' +    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
' +    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
' +    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
' +    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
' +    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
' +    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
' +    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
' +    'Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressionFilter - Unable to find: d:\\Desktop\\Neuer Ordner (2)/checkstyle-suppressions.xml
' +    '\tat com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
' +    '\tat com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
' +    '\tat com.shengchen.checkstyle.checker.CheckerService.setConfiguration(CheckerService.java:67)
' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.setConfiguration(DelegateCommandHandler.java:79)
' +    '\t... 17 more
' +    'Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: d:\\Desktop\\Neuer Ordner (2)/checkstyle-suppressions.xml
' +    '\tat com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:528)
' +    '\tat com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppressions(SuppressionsLoader.java:222)
' +    '\tat com.puppycrawl.tools.checkstyle.filters.SuppressionFilter.finishLocalSetup(SuppressionFilter.java:274)
' +    '\tat com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
' +    '\tat com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
' +    '\t... 20 more
',  level: 'info',  timestamp: '2021-02-23 10:45:48.242'}{  message: '[Error - 10:45:48] 23.02.2021, 10:45:48 Error in calling delegate command handler\n' +    'null\n' +    'java.lang.reflect.InvocationTargetException
' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
' +    '\tat java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
' +    '\tat java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
' +    '\tat java.base/java.lang.reflect.Method.invoke(Method.java:564)
' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.executeCommand(DelegateCommandHandler.java:58)
' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler$1.run(WorkspaceExecuteCommandHandler.java:215)
' +    '\tat org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:45)
' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.WorkspaceExecuteCommandHandler.executeCommand(WorkspaceExecuteCommandHandler.java:205)
' +    '\tat org.eclipse.jdt.ls.core.internal.handlers.JDTLanguageServer.lambda$3(JDTLanguageServer.java:497)
' +    '\tat org.eclipse.jdt.ls.core.internal.BaseJDTLanguageServer.lambda$0(BaseJDTLanguageServer.java:75)
' +    '\tat java.base/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:642)
' +    '\tat java.base/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:479)
' +    '\tat java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
' +    '\tat java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
' +    '\tat java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
' +    '\tat java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
' +    '\tat java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
' +    'Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module SuppressionFilter - Unable to find: d:\\Desktop\\Neuer Ordner (2)/checkstyle-suppressions.xml
' +    '\tat com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:482)
' +    '\tat com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
' +    '\tat com.shengchen.checkstyle.checker.CheckerService.setConfiguration(CheckerService.java:67)
' +    '\tat com.shengchen.checkstyle.runner.DelegateCommandHandler.setConfiguration(DelegateCommandHandler.java:79)
' +    '\t... 17 more
' +    'Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: d:\\Desktop\\Neuer Ordner (2)/checkstyle-suppressions.xml
' +    '\tat com.puppycrawl.tools.checkstyle.utils.CommonUtil.getUriByFilename(CommonUtil.java:528)
' +    '\tat com.puppycrawl.tools.checkstyle.filters.SuppressionsLoader.loadSuppressions(SuppressionsLoader.java:222)
' +    '\tat com.puppycrawl.tools.checkstyle.filters.SuppressionFilter.finishLocalSetup(SuppressionFilter.java:274)
' +    '\tat com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:197)
' +    '\tat com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:477)
' +    '\t... 20 more
',  level: 'info',  timestamp: '2021-02-23 10:45:48.243'}
```

**Comment by DaniGTA** [comment] 2021-02-23 09:56
In the error from the dev console i found this: `Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Unable to find: d:\\Desktop\\Neuer Ordner (2)/checkstyle-suppressions.xml` and i fixed my typo and now it works.

Thanks for the fast response.

**Comment by pappattila** [comment] 2021-02-23 10:10
hmm i got mine working with this setting file: https://github.com/checkstyle/checkstyle/blob/master/src/main/resources/google_checks.xml

**Comment by jdneo** [comment] 2021-02-23 11:24
Ok I'll close this issue since the problem is resolved.

**Closed by jdneo** 2021-02-23 11:24 UTC
Labels: needs more info

**Comment by themattman18** [comment] 2021-06-05 19:08
Opening the Java Extension Log File helped me resolve this issue. See https://github.com/microsoft/vscode-java-debug/issues/950#issuecomment-826219636
